name: Update Scopus Metrics

on:
  schedule:
    - cron: '0 0 * * 0'  # runs every Sunday at midnight UTC
  workflow_dispatch:     # also allows manual trigger

jobs:
  update-metrics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run script to fetch metrics and update file
        env:
          SCOPUS_API_KEY: ${{ secrets.SCOPUS_API_KEY }}
          SCOPUS_AUTHOR_ID: ${{ secrets.SCOPUS_AUTHOR_ID }}
        run: python fetch_scopus_metrics.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add metrics.json
          git diff --quiet --cached || git commit -m "Update Scopus metrics"
          git push
        # Continue even if no changes (to avoid errors if metrics unchanged)
        continue-on-error: true
